### ISSUE TITLE
Add support for 3D images

### ISSUE THREAD

**Issue by NotAPenguin0** [NotAPenguin0/phobos-rs#39]
Currently image view types are hardcoded to 2D.

**Comment by jedjoud10** [comment]
Are 3D images that much different when it comes to synchronization or do you just need to expose the view type? If it's not too hard I can go and expose the inner view type tbh (I'll need it for my engine anyway).

**Comment by NotAPenguin0** [comment]
It's just the view type and constructor parameters that are needed yeah, should be very simple.
