### ISSUE TITLE
Avoid polling fences in the Future implementation

### ISSUE THREAD

**Issue by pac85** [NotAPenguin0/phobos-rs#55]
As can be seen here https://github.com/NotAPenguin0/phobos-rs/blob/master/src/sync/fence.rs#L283
fences are polled, this means futures have a limited time granularity plus they keep spawning threads while waiting.

It should be possible to instead wait on the Fence from that thread and call wake after the wait.

An atomic can be used to make sure only one thread is spawned that waits on the fence. 

I will follow this up with a draft

**Comment by NotAPenguin0** [comment]
Implemented in #56
