### ISSUE TITLE
Type Checked Graphics/Render Pass Builder

### ISSUE THREAD

**Issue by jedjoud10** [NotAPenguin0/phobos-rs#63]
Currently, inside the ``PassBuilder``, the functions ``present``, ``color``, ``color_attachment``, ``clear_color_attachment``, ``load_color_attachment``, ``clear_depth_attachment``, ``clear_load_attachment``, ``depth_attachment``, ``resolve`` and ``resolve_depth`` are all present for any given ``ExecutionDomain`` D. These functions should be separately implemented for the ``Graphics`` domain since they are render/graphics operations. 

Also could help remove the ``Fails if this pass was not created using PassBuilder::render()`` case since it would be type checked, but only if we assume that all ``PassBuilders`` that are using the ``Graphics`` domain are going to be render passes (which is not necessarily true for all cases)

**Comment by NotAPenguin0** [comment]
`present` can be for both graphics and compute

**Comment by NotAPenguin0** [comment]
Part of this was implemented in #64, is there anything else in this issue that's not covered by that PR?

**Comment by jedjoud10** [comment]
Pretty sure that's all.
