### ISSUE TITLE
Small issue with ImgView wrapper when using non 0 base layer/base level.

### ISSUE THREAD

**Issue by jedjoud10** [NotAPenguin0/phobos-rs#65]
There might be a bug on lines 343-346 in image.rs due to the fact that we don't set the arguments of the created ImgView based on the given create info. 
https://github.com/NotAPenguin0/phobos-rs/blob/master/src/resource/image.rs#L343-L346

**Comment by NotAPenguin0** [comment]
That looks like a bug yeah, will fix
